# Generated by Django 5.2.1 on 2025-05-24 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
            ],
        ),
    ]
