# Generated by Django 5.2.1 on 2025-05-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_utilisateur_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='telechargements',
            field=models.ManyToManyField(blank=True, related_name='telecharge_par', to='dashboard.projetetudiant', verbose_name='Projets téléchargés'),
        ),
    ]
