# Generated by Django 5.2.1 on 2025-05-31 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_utilisateur_telechargements'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursenseignant',
            name='type_cours',
            field=models.CharField(choices=[('cours', 'Cours Magistral'), ('td', 'Travaux Dirigés'), ('tp', 'Travaux Pratiques'), ('support', 'Support de Cours'), ('examen', 'Examen')], default='cours', max_length=20),
        ),
        migrations.AddField(
            model_name='documentadministratif',
            name='est_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentadministratif',
            name='type_document',
            field=models.CharField(choices=[('circulaire', 'Circulaire'), ('note', 'Note de Service'), ('pv', 'Procès-Verbal'), ('decision', 'Décision'), ('rapport', 'Rapport'), ('autre', 'Autre')], default='circulaire', max_length=20),
        ),
        migrations.AddField(
            model_name='projetetudiant',
            name='mots_cles',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projetetudiant',
            name='type_projet',
            field=models.CharField(choices=[('pfe', "Projet de Fin d'Études"), ('memoire', 'Mémoire'), ('these', 'Thèse'), ('rapport', 'Rapport de Stage'), ('autre', 'Autre')], default='pfe', max_length=20),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.CreateModel(
            name='ScanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('projet', 'Projet Étudiant'), ('cours', 'Cours Enseignant'), ('document', 'Document Administratif')], max_length=20)),
                ('fichier_scan', models.FileField(upload_to='scans/')),
                ('date_scan', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('traite', 'Traité'), ('erreur', 'Erreur')], default='en_attente', max_length=20)),
                ('resultat_cours', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.coursenseignant')),
                ('resultat_document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.documentadministratif')),
                ('resultat_projet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.projetetudiant')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='coursenseignant',
            name='scan_provenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.scandocument'),
        ),
        migrations.AddField(
            model_name='documentadministratif',
            name='scan_provenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.scandocument'),
        ),
        migrations.AddField(
            model_name='projetetudiant',
            name='scan_provenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.scandocument'),
        ),
    ]
