# Generated by Django 5.2.1 on 2025-06-09 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_coursenseignant_type_cours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scandocument',
            name='fichier_scan',
            field=models.FileField(blank=True, null=True, upload_to='scans/'),
        ),
        migrations.CreateModel(
            name='ScanPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_page', models.PositiveIntegerField()),
                ('fichier_page', models.FileField(upload_to='scan_pages/')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='dashboard.scandocument')),
            ],
            options={
                'ordering': ['numero_page'],
            },
        ),
    ]
