# Generated by Django 5.2.1 on 2025-06-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_scandocument_fichier_scan_scanpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanpage',
            name='fichier_page',
            field=models.ImageField(upload_to='scan_pages/'),
        ),
    ]
